default:
  app:
    project: production
    source:
      targetRevision: HEAD

applications:
  demo-a:
    namespace: demo-a
    source:
      repoURL: 'https://github.com/louise-x/simple-k8s-demo.git'
      targetRevision: main
      path: proj-a/overlays/prod
    enabled: true
