{{- range $key,$val := .Values.applications -}}
{{- if $val.enabled -}}
{{ printf "\n" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: {{ $val.source.repo_type | default "git" }}
  url: {{ $val.source.repoURL }}
{{- end -}}
{{- end -}}